# https://taskfile.dev

version: '3'

vars:
    GREETING: Reading npy files in Odin

tasks:
    build:
        cmds:
        - odin build . -o:aggressive -out:./builds/python-numpy-npy-in-odin.exe
        silent: true
        generates:
            - ./python-numpy-npy-in-odin.exe

    npy:
        deps:
            - build
        cmds:
            - ./builds/python-numpy-npy-in-odin.exe {{.CLI_ARGS}}
        silent: false
        method: none

    npy-ints:
        aliases:
          - int
        deps:
            - build
        cmds:
            - ./builds/python-numpy-npy-in-odin.exe ./test_data/ints/b_5.npy
            - ./builds/python-numpy-npy-in-odin.exe ./test_data/ints/byte_5.npy
            - ./builds/python-numpy-npy-in-odin.exe ./test_data/ints/int8_5.npy
            - ./builds/python-numpy-npy-in-odin.exe ./test_data/ints/intc_5.npy
        silent: false
        method: none
