# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - odin build . -o:aggressive -show-timings -no-bounds-check -out:./builds/python-numpy-npy-in-odin.exe
    silent: true
    generates:
        - ./python-numpy-npy-in-odin.exe

  debug:
    cmds:
      - odin build . -o:aggressive -show-timings -no-bounds-check -debug -out:./builds/python-numpy-npy-in-odin.pdb
    silent: true
    generates:
        - ./python-numpy-npy-in-odin.pdb

  npy:
    cmds:
      - ./builds/python-numpy-npy-in-odin.exe {{.CLI_ARGS}}
    silent: false
    method: none

  npy-ints:
    aliases:
      - int
    cmds:
      - time bash ./scripts/test_all_ints.sh
    silent: false
    method: none

  npy-floats:
    aliases:
      - flt
    cmds:
      - time bash ./scripts/test_all_floats.sh
    silent: false
    method: none
